services:
  - mysql:latest

variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: test_database
  MYSQL_ROOT_PASSWORD: test_password

before_script:
  - apt-get update -y && apt-get install -y gradle openjdk-8-jdk libmysql-java

build:
  script:
    - gradle build -x test

test:
  script:
    - gradle test
